<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Google</name>
   <tag></tag>
   <elementGuidId>aa168e79-49a8-4377-992d-6e45de780435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ta-button--google__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='login-section']/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e57131eb-c981-42d2-9070-7e19ad8df77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ta-button--google__text</value>
      <webElementGuid>054c0b1a-5084-4db3-bcde-a3b6fcee238e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>ceb51403-a23b-455d-806f-9ee43e368baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-section&quot;)/div[2]/button[@class=&quot;ta-button ta-button--google&quot;]/span[@class=&quot;ta-button--google__text&quot;]</value>
      <webElementGuid>e6ec4c46-5b8d-4dd6-8be1-8eb30468dc09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='login-section']/div[2]/button/span</value>
      <webElementGuid>4cf9957b-d645-41f6-8b89-311161e4c1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or Sign in with'])[1]/following::span[1]</value>
      <webElementGuid>304d039b-4a77-4698-91e1-2f1d8d583379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[1]/following::span[2]</value>
      <webElementGuid>3ec7d114-50dc-4a32-9dbf-a5574e8dd8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Number : ${buildNumber}'])[1]/preceding::span[1]</value>
      <webElementGuid>4cd8f48e-53f3-4673-8bdb-a28444463646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Date: 2022-09-02 03:47:05'])[1]/preceding::span[1]</value>
      <webElementGuid>ea319ac0-3eca-48fc-a74f-34afc0b49982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Google']/parent::*</value>
      <webElementGuid>2e372670-c5b5-4105-af79-7e254db93c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>e278d82e-18e0-40cc-b9d3-dd9e3706f701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>91b1efc8-a177-4561-9673-2a3507535037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
