<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_TIBCO Spotfire Analyst</name>
   <tag></tag>
   <elementGuidId>fd485a53-a970-4f8c-ad06-31005f3cfe73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyLeftContainer']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e6d16729-f78a-47dd-a827-0f817422b5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIBCO Spotfire Analyst 
      	</value>
      <webElementGuid>b50b4f37-a4a6-445d-88c2-2968d0d5c488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyLeftContainer&quot;)/h2[1]</value>
      <webElementGuid>4b4c65c9-9114-4ee9-9b77-31c1f59181fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyLeftContainer']/h2</value>
      <webElementGuid>31aae171-9ddb-4730-9222-61c0185f39af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Detail'])[1]/following::h2[1]</value>
      <webElementGuid>6262acc1-18cc-44a6-94fc-a3cf7b96b2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X Close'])[1]/following::h2[1]</value>
      <webElementGuid>83638b22-f7f7-4cc7-b55d-a000a376c8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version(s)'])[1]/preceding::h2[1]</value>
      <webElementGuid>b77ac36c-5147-4160-a84e-068d2086d695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::h2[1]</value>
      <webElementGuid>7608061a-dcab-4be1-ae11-68c51cf48b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>048c3d64-6baa-4923-b513-78b7ed0243dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'TIBCO Spotfire Analyst 
      	' or . = 'TIBCO Spotfire Analyst 
      	')]</value>
      <webElementGuid>07dbf456-4df1-48a2-a9df-faedfa78ab1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
