<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACCOUNT ACCESS</name>
   <tag></tag>
   <elementGuidId>9d3a6c3b-487f-46ca-9f55-27669b8b0fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dk']/li/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ef40818-96f5-43a1-846f-a6327e128c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#actAccess</value>
      <webElementGuid>6e653cbd-6953-43c3-9bfc-fa630e3b4260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCOUNT ACCESS</value>
      <webElementGuid>ebe69fb2-c911-4a41-ae71-1f3364a77d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dk&quot;)/li[1]/h3[1]/a[1]</value>
      <webElementGuid>d4cff2d3-87da-41e4-b415-23657337a92c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dk']/li/h3/a</value>
      <webElementGuid>4818840b-fdb3-433f-9a03-9592587e64f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ACCOUNT ACCESS')]</value>
      <webElementGuid>dca9b6d4-9eaf-40b1-9798-a12c07a2747a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::a[1]</value>
      <webElementGuid>e0654ce8-0dbf-416f-bd25-39baca2205d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all products A-Z'])[1]/following::a[1]</value>
      <webElementGuid>5fa21840-afc1-4d9b-8af5-ec575f4262c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DOWNLOADS - General'])[1]/preceding::a[5]</value>
      <webElementGuid>f69490ed-5951-4e55-b857-fa83894ff4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DOWNLOADS - Troubleshooting'])[1]/preceding::a[6]</value>
      <webElementGuid>ea82fa72-2b22-4fe2-9041-923d7198d655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCOUNT ACCESS']/parent::*</value>
      <webElementGuid>5ab7871e-7eb1-4485-9bc8-43c80374b571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#actAccess')]</value>
      <webElementGuid>b56ae25e-0878-40b8-ae54-f866087da16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>e14f9ca8-73d1-4bd2-b32a-6e570313691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#actAccess' and (text() = 'ACCOUNT ACCESS' or . = 'ACCOUNT ACCESS')]</value>
      <webElementGuid>2374c84a-c1c7-47b0-a0f5-eede3cbe5f41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
