<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_USER MANAGEMENT</name>
   <tag></tag>
   <elementGuidId>fe87c373-46bc-4c93-818c-daf105d7319b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dk']/li[4]/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02498e0d-a947-4309-95dd-b14cd4bea017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#userAdmin</value>
      <webElementGuid>e6b2f63c-80a1-4849-8a48-8ae4b670dad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USER MANAGEMENT</value>
      <webElementGuid>12ba16c4-1ff7-449f-9645-58a2dc3def21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dk&quot;)/li[4]/h3[1]/a[1]</value>
      <webElementGuid>bb6748ff-e2aa-430f-8841-38fdbc53186a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dk']/li[4]/h3/a</value>
      <webElementGuid>c40352f4-00f4-4441-b743-dbaff5aba56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'USER MANAGEMENT')]</value>
      <webElementGuid>ed18bbac-9c37-4a09-8fbb-b32b4ddaa651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DOWNLOADS - Troubleshooting'])[1]/following::a[1]</value>
      <webElementGuid>77572ef6-8605-4efc-a5f2-d78676105c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DOWNLOADS - General'])[1]/following::a[2]</value>
      <webElementGuid>d96c78a4-50f3-4983-ac40-abb05a4b69b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MORE HELP'])[1]/preceding::a[1]</value>
      <webElementGuid>4d6357d2-cda2-437d-945b-7999fe7c3931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNT ACCESS'])[2]/preceding::a[2]</value>
      <webElementGuid>0e961594-01b3-4128-9f1d-7b3dbbea9662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='USER MANAGEMENT']/parent::*</value>
      <webElementGuid>49ffc9b7-1a73-4e60-bc1a-a0d1b6b9f8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#userAdmin')]</value>
      <webElementGuid>b1d8aca9-51fe-4e07-8326-c3eee9cad192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/h3/a</value>
      <webElementGuid>62655ff8-d487-4e11-b864-49b1faf7d00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#userAdmin' and (text() = 'USER MANAGEMENT' or . = 'USER MANAGEMENT')]</value>
      <webElementGuid>95df5c76-62dc-45e7-baac-ea1787a740a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
