<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SIGN OUT</name>
   <tag></tag>
   <elementGuidId>6696b383-9564-4a74-b702-1b626e6c40c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='storefrontSignout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#storefrontSignout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>535c4638-684a-4cc5-b262-38fcd33d2120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void();</value>
      <webElementGuid>8f20a16a-7c4b-402d-a855-c68643e88e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>storefrontSignout</value>
      <webElementGuid>7f14bc16-0849-4f4c-8ef1-f9346379d59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteCookie(),signOutMe();</value>
      <webElementGuid>c80be8a4-d518-4954-bb3a-555f6cdf661e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIGN OUT </value>
      <webElementGuid>f8a7bd17-a18c-4717-9d65-8ed998cbd65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storefrontSignout&quot;)</value>
      <webElementGuid>b8b35982-dd86-47aa-851d-9e01c0425919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='storefrontSignout']</value>
      <webElementGuid>19ab513b-d59e-41ee-a698-9a1a47c5ca70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='usernameSection']/li[2]/a</value>
      <webElementGuid>f44cc1ef-3f60-4a3c-a67f-9a3100f729df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SIGN OUT')]</value>
      <webElementGuid>7c4d587a-1a13-468c-a8bf-82f785dec86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance activity is going on, please come after some time.'])[1]/following::a[2]</value>
      <webElementGuid>fbf7e2fa-b26e-44ea-bf54-baa5447d8add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification:'])[3]/following::a[2]</value>
      <webElementGuid>2c8ed018-408e-47b9-8184-0c7478cb0a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[1]/preceding::a[1]</value>
      <webElementGuid>3e5b3928-6112-4aa3-bf41-98e519cfbc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/preceding::a[2]</value>
      <webElementGuid>ed6b0476-269d-4362-ba6b-ba06ec2febf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIGN OUT']/parent::*</value>
      <webElementGuid>a97723b6-dfbe-4c12-a5b4-f03b3b785692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void();')]</value>
      <webElementGuid>f8521e5f-d882-4f4c-ad18-7cb2265d8192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>4a8223c5-7620-4daf-99ad-850c19bad165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void();' and @id = 'storefrontSignout' and (text() = 'SIGN OUT ' or . = 'SIGN OUT ')]</value>
      <webElementGuid>0533603f-91a5-4364-af59-9ab6ba83da77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
