<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_all products A-Z_keyWords_1_2_3_4_5_6_7_8_9_10_11_12_13</name>
   <tag></tag>
   <elementGuidId>1f15de75-992f-494c-9a04-92d2a03caf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suggestKeywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suggestKeywords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbebb43b-050c-4fde-9721-f38c96a8151d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suggestKeywords</value>
      <webElementGuid>dabf5936-19d3-4a2f-877f-cae1b96e3788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97fc38ca-9f65-4a7c-b298-7890ff49244a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8e1fbbf-a2d3-4b0b-b67d-9921b38d5549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>search products or keywords</value>
      <webElementGuid>26bf8b3e-4d27-47d6-b5c5-f81c0e639ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyWords</value>
      <webElementGuid>6659a018-0116-46da-b57b-6805e7519cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if (this.value == '') {this.value = 'search products or keywords';}</value>
      <webElementGuid>6959c833-461d-4418-88e6-28cc14ccf60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if (this.value == 'search products or keywords') {this.value = '';}</value>
      <webElementGuid>404b29fd-d879-43c6-be72-f7559423b855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>75d7f0f0-3ef4-46c5-b2b9-1ef06b7915a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tibco Spotfire </value>
      <webElementGuid>c48afb58-6dc4-409e-879d-c7ae35a3da45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestKeywords&quot;)</value>
      <webElementGuid>71a10620-2e85-4bdc-9e48-c575420e86fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suggestKeywords']</value>
      <webElementGuid>ff619b47-795e-4205-9c84-fb5f15b15c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchContainer']/div[2]/ul/li[2]/div/input</value>
      <webElementGuid>f1df06b3-9563-46a5-b4bd-611be424b335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>8b9a5eb6-d6e6-4701-8a63-9f0ef472cdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'suggestKeywords' and @type = 'text' and @name = 'keyWords' and @title = 'Tibco Spotfire ']</value>
      <webElementGuid>d1f86aea-90af-41eb-8834-aec9a8b65fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
