<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_all products A-Z_searchBoxSubmit</name>
   <tag></tag>
   <elementGuidId>aa47b5a6-d561-442d-bb9b-3b45abbe7fd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBoxSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchBoxSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea88686d-8670-45a8-9cee-4f2f736a936c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBoxSubmit</value>
      <webElementGuid>f82adc73-5422-4eab-bd5b-2cb5f3247416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea36d1ef-51f4-459f-861d-caa5425f73a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBoxSubmit&quot;)</value>
      <webElementGuid>bf1b73cd-a554-4cad-8c35-1e08b86aa8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBoxSubmit']</value>
      <webElementGuid>4cc040a5-d36c-419a-8872-d271d820c532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchContainer']/div[2]/ul/li[2]/div/input[2]</value>
      <webElementGuid>9bc111d1-8d6d-4b6a-8d7d-de5c20e83fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>39640319-c4d4-4137-9b92-153a286d0a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchBoxSubmit' and @type = 'button']</value>
      <webElementGuid>cdb5807c-20f1-4397-84ff-b37cf20fc336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
