<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_all products A-Z_keyWords_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>5339a7c2-07e4-44a1-8ec7-9e17a3a9c4a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suggestKeywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suggestKeywords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35194ac9-3700-4fa8-8da9-91e4c26c4514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suggestKeywords</value>
      <webElementGuid>d89bd856-5cae-437a-8f35-be337b1d41de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b69b4bc9-ebbf-41f2-9c37-7aff8745269f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e08ae881-ce94-4e00-8e6e-fca5b5f8ede4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>search products or keywords</value>
      <webElementGuid>3b1b418c-9e6d-4f52-b283-1218e1f8a2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyWords</value>
      <webElementGuid>9f29c732-c00d-4611-8efd-4e9cf87dc108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if (this.value == '') {this.value = 'search products or keywords';}</value>
      <webElementGuid>88584fb9-bc31-4be7-9cb5-ff87c630edda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if (this.value == 'search products or keywords') {this.value = '';}</value>
      <webElementGuid>189984fb-6761-400b-abd5-8cf04ccd3258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input ac_loading</value>
      <webElementGuid>1de7bc53-2c0e-4d9f-a8e6-68ea1668d6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tibco Spot</value>
      <webElementGuid>7d31be6e-5cc5-48af-94c9-82b570baefe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestKeywords&quot;)</value>
      <webElementGuid>85c578fa-c554-4b07-86ad-da52c1b8abc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suggestKeywords']</value>
      <webElementGuid>ab0d83fa-5005-42f0-977b-bee934a15d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchContainer']/div[2]/ul/li[2]/div/input</value>
      <webElementGuid>3daeec2c-42b6-44ff-b5ce-a91531bc7024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>645590af-2863-4d8e-b2b2-cb733da8b4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'suggestKeywords' and @type = 'text' and @name = 'keyWords' and @title = 'Tibco Spot']</value>
      <webElementGuid>00ab25cc-7383-4e51-abdb-0b5f9052c3a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
