<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_all products A-Z_keyWords_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20</name>
   <tag></tag>
   <elementGuidId>d9f6d7ab-90ca-4823-8bd1-9d3ee1c0ce87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suggestKeywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suggestKeywords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1e90edb-b4ff-4546-9ec5-0f29ebf6e6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suggestKeywords</value>
      <webElementGuid>a58d86f2-e089-4070-b69e-038d2acba262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7613800-0563-4949-b99d-fbd79b39e4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>833d5d2f-9e3f-43d1-91fe-3774c2f61b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>search products or keywords</value>
      <webElementGuid>89e5e3a6-7996-4748-aec9-0e5f59f344d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyWords</value>
      <webElementGuid>15f6beaf-6bdc-44ac-a951-cbc9157897af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if (this.value == '') {this.value = 'search products or keywords';}</value>
      <webElementGuid>dde2eac2-744e-45e7-afda-45fe7a33359c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if (this.value == 'search products or keywords') {this.value = '';}</value>
      <webElementGuid>1ed52415-7b09-413b-93d1-df8331b4c0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>005ef9f5-62e5-42c1-8f61-3cfb90de6e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tibco Spotfire Analyst</value>
      <webElementGuid>7c6a46f4-7381-4c65-868e-fa8ba298a15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestKeywords&quot;)</value>
      <webElementGuid>df4622e1-8e88-47f2-8282-15decbf59206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suggestKeywords']</value>
      <webElementGuid>fb861732-a0af-4acd-9976-e98c4c0c79d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchContainer']/div[2]/ul/li[2]/div/input</value>
      <webElementGuid>68fc0a20-bd9a-4e73-8a3f-a6627f6a844a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>95398f25-a9ba-46ea-a159-231b4a621202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'suggestKeywords' and @type = 'text' and @name = 'keyWords' and @title = 'Tibco Spotfire Analyst']</value>
      <webElementGuid>2950ba52-e4db-48a0-802b-c2aecc9830f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
