<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_all products A-Z_keyWords_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15</name>
   <tag></tag>
   <elementGuidId>ef21171c-449a-4e71-b0c7-2796202cf9c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suggestKeywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suggestKeywords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb36cf16-4680-48f2-87e2-57140ac309fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suggestKeywords</value>
      <webElementGuid>ce105351-0301-4fc0-b114-4565d8997736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5327b28b-f5d2-4f7a-aeed-2dfc9ea8f408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af5c2801-2d01-4b9c-ab4b-cdd02cf8c649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>search products or keywords</value>
      <webElementGuid>0ff623df-a0ed-4845-a085-1ec825640d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyWords</value>
      <webElementGuid>5805222b-a676-4a1a-9f63-5459d3781757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if (this.value == '') {this.value = 'search products or keywords';}</value>
      <webElementGuid>f90cddc0-6871-4cb0-ae15-93a503dc1e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if (this.value == 'search products or keywords') {this.value = '';}</value>
      <webElementGuid>38a6d54b-3f0b-4915-9861-d7cb82e12abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>b959e4ea-5f25-4d23-8c9f-8602d186f357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tibco Spotfire An</value>
      <webElementGuid>03199f98-36ae-43ca-9b0e-c5f72e1bba8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestKeywords&quot;)</value>
      <webElementGuid>6d89890c-59c2-435f-baa3-d64320bb10f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suggestKeywords']</value>
      <webElementGuid>a28686f5-7d7a-42ac-8dc9-cbc118e5eec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchContainer']/div[2]/ul/li[2]/div/input</value>
      <webElementGuid>7bdfa8dc-e3e4-4f0b-ba95-72df14834095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>646d051a-04e7-466a-9395-e7f4b9e67202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'suggestKeywords' and @type = 'text' and @name = 'keyWords' and @title = 'Tibco Spotfire An']</value>
      <webElementGuid>eb8bc553-e296-4091-9d6c-72c0fcc6c90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
