<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_all products A-Z_keyWords_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>b6aa25a5-c041-4c96-9333-2aaffc7719a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suggestKeywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suggestKeywords</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66b2c9ef-05c9-439a-874b-baad1ea7eb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suggestKeywords</value>
      <webElementGuid>dc5d49eb-ec1b-4a47-bc12-39c61b14f706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de293791-4a53-4716-bf32-5e5d4995c5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c17ba158-c863-435e-b0e8-891b5fc5ecd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>search products or keywords</value>
      <webElementGuid>43872d3a-94d1-49cb-afde-8bbe3b676b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyWords</value>
      <webElementGuid>6d392475-9e27-431c-843f-6d91758b3848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if (this.value == '') {this.value = 'search products or keywords';}</value>
      <webElementGuid>2bcb94b0-2795-4c6a-9f29-ff772ba42ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if (this.value == 'search products or keywords') {this.value = '';}</value>
      <webElementGuid>5f836dd9-a30a-461f-a464-aecdb8703ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>9b4b4098-ce99-470f-9341-34451ccd7d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tibc</value>
      <webElementGuid>9448d2fd-2e1b-4124-aaf5-b6f7541b4283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestKeywords&quot;)</value>
      <webElementGuid>a3fb7bed-979c-4632-a1ad-6032423031eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suggestKeywords']</value>
      <webElementGuid>0bbf1870-7f17-4deb-b4b8-8ff583501aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchContainer']/div[2]/ul/li[2]/div/input</value>
      <webElementGuid>53d787e9-b5cc-4350-bf4b-952895169cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>2f449d33-05fb-4a65-999f-49cda5aa1968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'suggestKeywords' and @type = 'text' and @name = 'keyWords' and @title = 'Tibc']</value>
      <webElementGuid>a4d6f222-4469-4c33-a51d-8c842af010fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
