<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Analyst</name>
   <tag></tag>
   <elementGuidId>8107301a-73da-4cf4-8edf-b0e19656df04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-grid-1']/ul/li/p/a/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6716e7ad-74fa-48ce-b63d-08a015046ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highlight</value>
      <webElementGuid>7718994a-5411-45e0-964c-28727edcc7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Analyst</value>
      <webElementGuid>983ae318-11d5-4477-a53d-a0046850ff5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-grid-1&quot;)/ul[@class=&quot;product&quot;]/li[@class=&quot;product-item-name&quot;]/p[@class=&quot;prod-name&quot;]/a[1]/span[@class=&quot;highlight&quot;]</value>
      <webElementGuid>3bdb0a73-74b6-47ee-8829-c187322892e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EdeliveryProductSearch_OR/Page_eDelivery Site/iframe_TypeAllProductsComponents_iframe1</value>
      <webElementGuid>55807c10-8a9c-453d-b6a3-d858ff4e8914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-grid-1']/ul/li/p/a/span[3]</value>
      <webElementGuid>2b6ee9ed-5b99-45cf-8969-20e53a5765ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spotfire'])[1]/following::span[1]</value>
      <webElementGuid>2417f447-c646-451b-bf5f-6e2043756212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO'])[1]/following::span[2]</value>
      <webElementGuid>ce5d41f2-e96b-4d64-95d2-37e84948c315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO'])[2]/preceding::span[1]</value>
      <webElementGuid>520a6337-eb81-4a7c-aa96-2675b36ed083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spotfire'])[2]/preceding::span[2]</value>
      <webElementGuid>62efce83-0b91-451d-914c-1ed5b476d026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Analyst']/parent::*</value>
      <webElementGuid>c84371cf-49bc-432c-89c3-e407b9f1c1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>13a3ec03-3474-4f13-b56f-ad0f6889645f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Analyst' or . = 'Analyst')]</value>
      <webElementGuid>c5ef399a-39f3-41d2-ac3f-642a62da4d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
