<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_License Keys</name>
   <tag></tag>
   <elementGuidId>cca16fd0-a8f7-463a-bcbf-c02ddf158430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#viewlicensekeys</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='viewlicensekeys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>695044b5-c326-4eed-89e2-b1508e430095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/view-licensekey.ep</value>
      <webElementGuid>0f5d5512-4c45-486e-91f4-88bf6be612f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewlicensekeys</value>
      <webElementGuid>365da2d9-0c68-4ec7-83eb-dca1e28441a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>License Keys</value>
      <webElementGuid>ed57cb80-56a6-4e5d-a9e9-3c1f5943808a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewlicensekeys&quot;)</value>
      <webElementGuid>5701ed27-b028-42e8-bf6a-e0acec941705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='viewlicensekeys']</value>
      <webElementGuid>e73b43ec-6176-4c02-8e22-6b52c8417872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='leftNav-license']/li[4]/a</value>
      <webElementGuid>09117e27-8a2c-4a03-a04a-320831e24026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'License Keys')]</value>
      <webElementGuid>e3a4c967-1be5-4bf5-9c54-0c9d442ba1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Notifications'])[1]/following::a[1]</value>
      <webElementGuid>df92db7c-d869-4331-846b-2db1fd6b7398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::a[2]</value>
      <webElementGuid>139b9b52-3623-40be-89d2-334f80fcf1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO Jaspersoft License Keys'])[1]/preceding::a[1]</value>
      <webElementGuid>a0f627f5-e946-49f3-94d1-1db9ac821741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must enter at least one search option.'])[1]/preceding::a[1]</value>
      <webElementGuid>af1149bd-6d83-4ffd-8ded-951d030704db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/view-licensekey.ep')]</value>
      <webElementGuid>8a558cb7-ff50-48ca-abca-53bd7c756a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[4]/a</value>
      <webElementGuid>1cf750c4-6e22-4c57-a438-6fae262c7a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/view-licensekey.ep' and @id = 'viewlicensekeys' and (text() = 'License Keys' or . = 'License Keys')]</value>
      <webElementGuid>e0bd6660-ee87-4e92-8589-3d947c18ba77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
