<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Enterprise</name>
   <tag></tag>
   <elementGuidId>0346bc30-06c6-48d4-8630-4041a53e1811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1C']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0cf3aff-58a2-4da9-9f12-61c650f72508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/admin/manage-enterprise.ep</value>
      <webElementGuid>6d99d43b-37c6-4cb7-adce-e617e9cf380b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>dcf77511-96da-4c8b-9007-f232519348bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Enterprise</value>
      <webElementGuid>ea96cbba-9e07-482a-9c04-544ae6a23b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1C&quot;)/ul[@class=&quot;subnav&quot;]/li[1]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>e177650d-582d-4189-b08e-92bb2937e685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1C']/ul/li/a</value>
      <webElementGuid>582404d3-a9da-44b9-a3b5-6c6a33b56144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Enterprise')]</value>
      <webElementGuid>556b75dd-72ad-4009-a88e-0c04cd5c9ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise'])[2]/following::a[1]</value>
      <webElementGuid>10e034be-0c7c-4aad-9d6d-2e8021ee80fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::a[1]</value>
      <webElementGuid>3f3d8eb0-ac3f-47d3-993c-36ad1f5fe639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Enterprise'])[1]/preceding::a[1]</value>
      <webElementGuid>a8a3dcee-ac7a-4bb3-8e59-6e59e31b034d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Created Successfully'])[1]/preceding::a[2]</value>
      <webElementGuid>bf71d39b-e957-4932-b382-0c7485100129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/storefront/admin/manage-enterprise.ep')])[2]</value>
      <webElementGuid>d31f09d2-d475-455a-88f6-3b42223339d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li/a</value>
      <webElementGuid>0f2df400-08e3-4261-b73f-eb5a625b197d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/admin/manage-enterprise.ep' and (text() = 'Manage Enterprise' or . = 'Manage Enterprise')]</value>
      <webElementGuid>50044abc-8af6-43e6-95d2-177a481139ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
