<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Documentation</name>
   <tag></tag>
   <elementGuidId>41a4a907-3479-467f-9b67-5c845ed2f181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='additionLink']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ece5098-2242-4f27-b77f-1b8fff12124a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://docs.tibco.com/</value>
      <webElementGuid>4877e03f-a6a7-4fc5-83dd-5d21c8507e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a2267ad5-2a5e-465f-8a01-ad3174b3b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>97839c58-90fd-432e-8080-4afcde42e5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additionLink&quot;)/ul[1]/li[3]/a[1]</value>
      <webElementGuid>b69ae4d6-3a30-43fb-9ae7-ea4348bacfed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='additionLink']/ul/li[3]/a</value>
      <webElementGuid>858ddee5-2a5f-42a8-96e2-f50a0142c6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Documentation')]</value>
      <webElementGuid>701f08f0-b19a-4085-ac5e-3426383cb230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/following::a[1]</value>
      <webElementGuid>ec1ee506-47e2-4a20-b9b5-7d8796ec6f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO'])[1]/following::a[2]</value>
      <webElementGuid>cb8d9d6c-a5bb-4d65-832e-77cdc1f7e6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2022 TIBCO Software Inc. All Rights Reserved.'])[1]/preceding::a[1]</value>
      <webElementGuid>a009d0ed-f365-4f34-a8d4-b57288d516ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::a[1]</value>
      <webElementGuid>fa8ec9d4-6a70-46bc-aff9-5413525d0388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documentation']/parent::*</value>
      <webElementGuid>0412c7f8-8246-4dc1-a6d3-2dd9dfb2eb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://docs.tibco.com/')]</value>
      <webElementGuid>61331909-0df2-4c7a-9cb9-b3842ecd6ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/ul/li[3]/a</value>
      <webElementGuid>de9ef65a-f45b-4a37-a6ca-6c0601a3bc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://docs.tibco.com/' and (text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>bde8154b-8d7d-4fd7-b15b-b455a9cf6d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
