<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This site uses cookies. By continuing t_20f0f8</name>
   <tag></tag>
   <elementGuidId>3230e1a2-f16f-40d5-8a98-57595da848c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookiesWarningActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cookiesWarningActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0d75943-1f95-44bd-b7c4-02a3fbe693a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiesWarningActive</value>
      <webElementGuid>af5b31f5-99f2-4acb-90de-90250a2dd6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookie-noticebar</value>
      <webElementGuid>a76b2f02-33b6-4b8c-a90e-c8566e9c321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This site uses cookies. By continuing to browse the site you are agreeing to our use of cookies.Read our Cookies and Privacy Policy.Notification: Maintenance activity is going on, please come after some time.X</value>
      <webElementGuid>6cd5fa9f-c965-4d63-a68c-adbbd518f225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiesWarningActive&quot;)</value>
      <webElementGuid>1d78a145-5ae3-4d9f-bc8b-ec62b8cccfc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cookiesWarningActive']</value>
      <webElementGuid>ebbce1d7-8856-4e1e-ba2d-7ae5ffc0ac9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiesWarning']/div</value>
      <webElementGuid>126c15fd-e5b1-4108-a1d2-fc2d54a508ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='for System Maintenance.'])[1]/following::div[3]</value>
      <webElementGuid>cfd6a958-179f-4529-a246-6b2d1324a4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between'])[1]/following::div[3]</value>
      <webElementGuid>f71623b7-3648-42d6-b6f5-f355b1297e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>524f0933-5a95-4351-9966-7ee070404519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cookiesWarningActive' and (text() = 'This site uses cookies. By continuing to browse the site you are agreeing to our use of cookies.Read our Cookies and Privacy Policy.Notification: Maintenance activity is going on, please come after some time.X' or . = 'This site uses cookies. By continuing to browse the site you are agreeing to our use of cookies.Read our Cookies and Privacy Policy.Notification: Maintenance activity is going on, please come after some time.X')]</value>
      <webElementGuid>e3223e33-136b-4bc9-9671-400f30915bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
