<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MY ACCOUNT</name>
   <tag></tag>
   <elementGuidId>a88913ee-e875-484d-91f8-daab4fc6795f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='usernameSection']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bcd7f481-e1d4-4c37-ae57-b07871130ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/manage-account.ep</value>
      <webElementGuid>4fa5758c-40b3-431e-bc76-a434842a4a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MY ACCOUNT</value>
      <webElementGuid>04d70e8e-1767-4e76-ad09-2c6e9349ab9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernameSection&quot;)/li[3]/a[1]</value>
      <webElementGuid>a8cfe1c6-039c-4b95-9c78-5e82b229c82a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='usernameSection']/li[3]/a</value>
      <webElementGuid>7fc7b123-2645-4783-882d-c431c0941946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MY ACCOUNT')]</value>
      <webElementGuid>cf69fddf-3cb1-4a8f-96a7-d3bb50189f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN OUT'])[1]/following::a[1]</value>
      <webElementGuid>c70a6736-f22d-41aa-826e-2fb44b62677b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance activity is going on, please come after some time.'])[1]/following::a[3]</value>
      <webElementGuid>09391498-97be-4a58-97fc-45cbeb1df76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN'])[1]/preceding::a[1]</value>
      <webElementGuid>9eda7865-6b13-4e45-a462-f0d5cf1d3bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/preceding::a[2]</value>
      <webElementGuid>579e3742-4da9-46b0-b912-4d56ebb3c539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MY ACCOUNT']/parent::*</value>
      <webElementGuid>e5bec5a0-5856-4949-a239-572a0ae061aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/manage-account.ep')]</value>
      <webElementGuid>c93bc229-9611-4625-8f10-8487c1eeb818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>fc7fd9a7-e6ed-4a2d-9a61-921a63580ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/manage-account.ep' and (text() = 'MY ACCOUNT' or . = 'MY ACCOUNT')]</value>
      <webElementGuid>87062bab-9166-485c-a8de-e014c84b155a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
