<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TIBCO</name>
   <tag></tag>
   <elementGuidId>8eefd6b9-8d4b-4b55-a437-aa1d0587b799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#additionLink > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='additionLink']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6285b1f3-0f23-49e7-80e8-90c520efe6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.tibco.com/</value>
      <webElementGuid>efbc0059-48e0-41e0-a249-8f6136c35e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6a512211-36d3-4da9-9ebc-b205301cd102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIBCO</value>
      <webElementGuid>ec5d03db-40f5-4250-b0a1-fb0a2b636252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additionLink&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>00de7341-bb39-412f-999e-46d4ba239bf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='additionLink']/ul/li/a</value>
      <webElementGuid>bedf42a6-173c-4305-b8bd-5f093f03faed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'TIBCO')])[4]</value>
      <webElementGuid>98a1f859-de96-4ba6-ab4e-eb48ce0a21a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more'])[3]/following::a[1]</value>
      <webElementGuid>93393127-50cf-43c9-962b-13edcec40302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO Nimbus'])[1]/following::a[2]</value>
      <webElementGuid>3983f2cc-797f-452f-8e2a-f0a6e15106ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/preceding::a[1]</value>
      <webElementGuid>c331eb46-8a81-44ea-828c-7d36e94bba5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[2]</value>
      <webElementGuid>f80412e5-6a99-4e9b-ba0c-a9fb07a0f882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TIBCO']/parent::*</value>
      <webElementGuid>4eb0c5a1-42a4-411b-8e4a-75a74dd0135c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.tibco.com/']</value>
      <webElementGuid>52f87cc8-da0f-41e6-8504-063b49a9e04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/ul/li/a</value>
      <webElementGuid>234a7dc3-1fbb-45ff-8e00-f64298dbc016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.tibco.com/' and (text() = 'TIBCO' or . = 'TIBCO')]</value>
      <webElementGuid>c28b125b-e67e-41eb-bf97-e3837a8eee3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
