<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enterprise</name>
   <tag></tag>
   <elementGuidId>46d19a38-0663-47a6-8e0f-600521f0c185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Enterprise</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Enterprise']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c219bfad-fa68-48b6-a07a-c4918ab7cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/admin/manage-enterprise.ep</value>
      <webElementGuid>a36f06c8-7dcc-4351-a88d-15025ba0eedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Enterprise</value>
      <webElementGuid>f8f9c147-1625-409d-b09b-024d249ecc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enterprise</value>
      <webElementGuid>ed66f328-df3e-4796-aebf-b71c6c9f7b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Enterprise&quot;)</value>
      <webElementGuid>615c67ba-0be6-4f2e-ac3a-ad7a003a7655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Enterprise']</value>
      <webElementGuid>bb103279-3b5a-4e23-86f1-379e6833ed37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyAdminLeftContainer']/ul/li/a</value>
      <webElementGuid>b46b5a79-d00c-4a0a-95fc-e9e4afc306c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enterprise')]</value>
      <webElementGuid>8681384e-2a16-45f4-87d9-d597220b4c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Tool'])[1]/following::a[1]</value>
      <webElementGuid>49c57726-1a4a-4e67-b05b-6674183907a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all products A-Z'])[1]/following::a[1]</value>
      <webElementGuid>80d6129b-eaef-45c6-89d8-e26c9f2bc933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[1]</value>
      <webElementGuid>06cad400-afe5-407c-a585-02515b7f4162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/preceding::a[2]</value>
      <webElementGuid>3565d48e-aafa-42ba-b1ab-151d014fbccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enterprise']/parent::*</value>
      <webElementGuid>25e6fb1e-d170-4d57-89ca-f7815b37c74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/admin/manage-enterprise.ep')]</value>
      <webElementGuid>a5ab8833-58de-4521-b996-e1926e790b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/a</value>
      <webElementGuid>20577cbb-29f9-48ff-8a2e-868ec61d3176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/admin/manage-enterprise.ep' and @id = 'Enterprise' and (text() = 'Enterprise' or . = 'Enterprise')]</value>
      <webElementGuid>b7dddd79-fb15-4fa9-8d9c-8fb1b9de0c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
