<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_License Keys</name>
   <tag></tag>
   <elementGuidId>1bb38b21-8fa4-4ef4-a024-39b4308b5a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#viewlicensekeys</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='viewlicensekeys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3239322d-6cb6-4dce-91c9-0a9c6d9ee013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/view-licensekey.ep</value>
      <webElementGuid>2172e926-ffb0-49ea-b2ff-c49543f5a2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewlicensekeys</value>
      <webElementGuid>c30836d3-a9d9-408b-86bf-23943e95eb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>License Keys</value>
      <webElementGuid>953b1840-d229-41cf-83ae-661e3b1c951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewlicensekeys&quot;)</value>
      <webElementGuid>c376a258-5350-4ce2-8c00-5faa6e9b354c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='viewlicensekeys']</value>
      <webElementGuid>14688068-18f6-4a26-bd2c-872b6ca091de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDwnLeftContainer']/ul/li[4]/a</value>
      <webElementGuid>83a33f2c-0bd2-450d-b905-33e2fda94ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'License Keys')]</value>
      <webElementGuid>cf5900a4-2563-43cc-af8e-06927a6bf717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Notifications'])[1]/following::a[1]</value>
      <webElementGuid>ff5108da-6a01-4abc-8fd2-e2698ae4c540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::a[2]</value>
      <webElementGuid>98dcebed-7e83-40f9-9139-9ba967bd3ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download History'])[3]/preceding::a[1]</value>
      <webElementGuid>209a31d3-52f5-47a9-9349-1095749a9d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='License Keys']/parent::*</value>
      <webElementGuid>bb3f5ee7-0dd2-4e74-943f-ce9b716f7157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/view-licensekey.ep')]</value>
      <webElementGuid>e358cffa-ec49-4aa4-9069-0372f93399ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[4]/a</value>
      <webElementGuid>8e22b8d3-23e0-422d-865d-b68dab2e05a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/view-licensekey.ep' and @id = 'viewlicensekeys' and (text() = 'License Keys' or . = 'License Keys')]</value>
      <webElementGuid>58d05cbd-8895-44f3-bdf1-02d48f8810d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
