<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EULA</name>
   <tag></tag>
   <elementGuidId>555163c2-417a-41f3-9ae1-53976f686706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.actAccess0.disNone > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyFAQRightContainer']/ul/li[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8aedc0d-8b61-4590-94c8-8b768947e96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.tibco.com/assets/blt59b361e6644c8d3a/tibco-end-user-license-agreement_tcm8-9378.pdf</value>
      <webElementGuid>94099ddd-dd56-4926-b3de-425aa8f1fafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>60f5b745-3680-4c05-bb5d-19884280332b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EULA</value>
      <webElementGuid>285fdc53-3cd6-4263-afe4-8a25c57b6e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyFAQRightContainer&quot;)/ul[1]/li[5]/div[@class=&quot;actAccess0 disNone&quot;]/a[1]</value>
      <webElementGuid>8401f236-c8ba-4f22-b234-fe5bc30e3880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyFAQRightContainer']/ul/li[5]/div/a</value>
      <webElementGuid>135a9cec-e023-4d1d-b72f-40406586bd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EULA')]</value>
      <webElementGuid>8aca3866-7a47-4cc6-8376-69afae2f4d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I’m an admin. Who can I give download access to?'])[1]/following::a[1]</value>
      <webElementGuid>50f82320-b1f3-4ca3-8c79-5df4c8a027e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will my eDelivery session time out if I’m inactive?'])[1]/following::a[1]</value>
      <webElementGuid>bbcb7794-3871-4c0b-ad20-740330de6892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do I need to enable cookies to use TIBCO eDelivery?'])[1]/preceding::a[1]</value>
      <webElementGuid>85894270-1e29-440a-81f7-e95f15f0fd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is JavaScript required to use this site?'])[1]/preceding::a[1]</value>
      <webElementGuid>73de2ebb-8063-4dc5-9d0d-dd866edd21cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EULA']/parent::*</value>
      <webElementGuid>3895fe0e-bf4a-42f4-b400-fae5bf697e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.tibco.com/assets/blt59b361e6644c8d3a/tibco-end-user-license-agreement_tcm8-9378.pdf']</value>
      <webElementGuid>22cb3b6d-0bd7-4130-b60e-3a47c4a6124b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>14ddcf1b-432c-4f10-ae21-ddd7162cb881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.tibco.com/assets/blt59b361e6644c8d3a/tibco-end-user-license-agreement_tcm8-9378.pdf' and (text() = 'EULA' or . = 'EULA')]</value>
      <webElementGuid>608da294-feca-4517-b1eb-cef30ebeab59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
