<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SIGN OUT</name>
   <tag></tag>
   <elementGuidId>cb125a9e-f4c0-422e-a7fb-03e79835d166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#storefrontSignout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='storefrontSignout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe7790ec-90bc-482a-95af-476d3842b7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void();</value>
      <webElementGuid>c4fca279-e64c-49df-bd9d-4ab61045e49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>storefrontSignout</value>
      <webElementGuid>642bc2d8-330d-4fe5-8d45-fdb44005594b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteCookie(),signOutMe();</value>
      <webElementGuid>4d906124-9537-482c-b373-5bcdad0ed78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIGN OUT </value>
      <webElementGuid>726c9c9b-67e4-4d99-a529-e09d6f65711b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storefrontSignout&quot;)</value>
      <webElementGuid>292ee397-cfe9-4c24-878e-8b60d47917e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='storefrontSignout']</value>
      <webElementGuid>5dde558e-16a4-4812-b841-be06bb0eba19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='usernameSection']/li[2]/a</value>
      <webElementGuid>dae26614-fa68-4747-9a60-4461cdb8b28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SIGN OUT')]</value>
      <webElementGuid>744ea5e7-fe58-447a-9a91-f701793a32fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance activity is going on, please come after some time.'])[1]/following::a[2]</value>
      <webElementGuid>1f0b6dcb-6497-47b1-a2c6-d9e94e919952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification:'])[3]/following::a[2]</value>
      <webElementGuid>b26c79a1-0915-425f-b336-921274a19db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[1]/preceding::a[1]</value>
      <webElementGuid>809aac9a-8abd-4ce7-b7a7-ef2e31391996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN'])[1]/preceding::a[2]</value>
      <webElementGuid>f554f3c8-8ceb-4506-957f-7dae6b150e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIGN OUT']/parent::*</value>
      <webElementGuid>ea3fb99a-9c96-464f-8691-653583a5bbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void();')]</value>
      <webElementGuid>ec418deb-6245-4c93-95df-cf7c272ac335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>1f0822aa-178c-4df6-95cd-6ea35a35d8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void();' and @id = 'storefrontSignout' and (text() = 'SIGN OUT ' or . = 'SIGN OUT ')]</value>
      <webElementGuid>ab099dbe-37fc-4f62-b9a0-2ec6fa6bd220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
