<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Burhade</name>
   <tag></tag>
   <elementGuidId>c8333473-3d9c-4b8d-87a5-c31bcbe4d27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myProfileDiv']/table/tbody/tr[3]/td[2]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>9e1f801b-9e9a-47ee-9fd0-e8ecf0321ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Burhade</value>
      <webElementGuid>109ea872-3143-44c3-8086-8d2e3817d63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myProfileDiv&quot;)/table[@class=&quot;personalinfo&quot;]/tbody[1]/tr[3]/td[2]/b[1]</value>
      <webElementGuid>802478fa-6f98-43aa-b817-3ecadfb02c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myProfileDiv']/table/tbody/tr[3]/td[2]/b</value>
      <webElementGuid>569fa440-e8ae-4750-b775-7ca935bb2393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name:'])[1]/following::b[1]</value>
      <webElementGuid>dd793a68-17a9-4b79-a718-d185e4a0f8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gaurav'])[1]/following::b[1]</value>
      <webElementGuid>483332b1-77c8-4458-b080-91cba084eece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::b[2]</value>
      <webElementGuid>e34b0839-5e76-4179-9c1b-56486d6b2667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/preceding::b[2]</value>
      <webElementGuid>19560902-0f2d-4f2a-8611-b846011727c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Burhade']/parent::*</value>
      <webElementGuid>23e791dc-b2a7-40f6-a004-0e2c13185179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/b</value>
      <webElementGuid>215b390f-89a3-4f84-b0be-e1738d566fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Burhade' or . = 'Burhade')]</value>
      <webElementGuid>42081a74-173c-4c47-a80a-ca85eeb2227d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
