<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_gmadhavrtibco.com</name>
   <tag></tag>
   <elementGuidId>4bd85590-8e07-4500-a63b-c8037d0b6862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myProfileDiv']/table/tbody/tr/td[2]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8ee63622-3278-4280-b1f1-75503c00d05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gmadhavr@tibco.com</value>
      <webElementGuid>f1ff72b3-2682-438f-8edf-b216a026ecb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myProfileDiv&quot;)/table[@class=&quot;personalinfo&quot;]/tbody[1]/tr[1]/td[2]/b[1]</value>
      <webElementGuid>9138e309-cff5-49ae-ade7-408f5236c3b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myProfileDiv']/table/tbody/tr/td[2]/b</value>
      <webElementGuid>2189f3df-cbd7-4c5c-b09b-24104cee7776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address:'])[1]/following::b[1]</value>
      <webElementGuid>4aee0567-370e-4ff4-82f4-432a3c97b19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Information'])[1]/following::b[1]</value>
      <webElementGuid>a4b7d772-9911-4d75-b630-857dfb8cf4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name:'])[1]/preceding::b[1]</value>
      <webElementGuid>91d3258a-bf6a-4d67-8102-4d025b73fa09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gaurav'])[1]/preceding::b[1]</value>
      <webElementGuid>3e66acd2-45b8-46f0-b3b9-6bcf4e5f1c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='gmadhavr@tibco.com']/parent::*</value>
      <webElementGuid>efcb284c-6bf5-4fa6-8ee9-6568fc97b574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/b</value>
      <webElementGuid>c0ddc744-4cd0-4291-aac8-93deec956d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'gmadhavr@tibco.com' or . = 'gmadhavr@tibco.com')]</value>
      <webElementGuid>29aa85e1-655f-419f-9f88-d16d549f54c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
