<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_IT - Custom Software Engineering</name>
   <tag></tag>
   <elementGuidId>dfa651f4-846e-4fbb-88bd-cd1de3ad6a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myProfileDiv']/table/tbody/tr[8]/td[2]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>d2307e85-d181-4799-a438-2f117d48d4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IT - Custom Software Engineering</value>
      <webElementGuid>a3cf3894-e0d3-4787-8e8b-3b20f6d355f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myProfileDiv&quot;)/table[@class=&quot;personalinfo&quot;]/tbody[1]/tr[8]/td[2]/b[1]</value>
      <webElementGuid>8a7ad82a-9715-4dfd-a025-dc147540f9a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myProfileDiv']/table/tbody/tr[8]/td[2]/b</value>
      <webElementGuid>4406bb38-b67c-4bc0-a15c-60c88fa76bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department name:'])[1]/following::b[1]</value>
      <webElementGuid>c59b00aa-21c6-4468-8b2e-020a8e9d5563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FULFILLMENT'])[1]/following::b[1]</value>
      <webElementGuid>0c8b1bff-9a93-461c-b745-eea51921b20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO IT Helpdesk'])[1]/preceding::b[2]</value>
      <webElementGuid>7448692f-bf17-43e6-ad57-21659a3741f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IT - Custom Software Engineering']/parent::*</value>
      <webElementGuid>a510430c-292c-4024-9bce-7ebeb20edc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/b</value>
      <webElementGuid>1cefa76c-830c-42c3-afd3-fa5405198033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'IT - Custom Software Engineering' or . = 'IT - Custom Software Engineering')]</value>
      <webElementGuid>2319a50f-0186-4eea-ac99-d24ff7d0c904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
