<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Email address</name>
   <tag></tag>
   <elementGuidId>4c4447dc-5438-4bb8-a9c6-8a4f1de0ae3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myProfileDiv']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5b27a1ab-a96f-4c01-b4bb-3873a7f7dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email address:</value>
      <webElementGuid>8a2d9a5e-13aa-4c32-a2ea-b676aeebce18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myProfileDiv&quot;)/table[@class=&quot;personalinfo&quot;]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>3d32c091-cc4f-4ec6-b2fa-7514fca14b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myProfileDiv']/table/tbody/tr/td</value>
      <webElementGuid>d1d9f75c-9f2e-4b79-a045-ef6403fc0f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Information'])[1]/following::td[1]</value>
      <webElementGuid>45225b93-448e-4e7f-9b10-b1ea6ba4954b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[2]/following::td[1]</value>
      <webElementGuid>3bf8ed98-3d7a-4800-8afe-13cc5fb74c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gmadhavr@tibco.com'])[1]/preceding::td[1]</value>
      <webElementGuid>1b96310d-17f4-4b6d-b8f5-83b6992cc363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name:'])[1]/preceding::td[2]</value>
      <webElementGuid>1bb17821-73b4-41b3-9c52-8922db5adcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email address:']/parent::*</value>
      <webElementGuid>b2cb4fb3-3830-4984-8b5b-3b51a256d179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>01e24778-d698-4833-a3bb-d1f33514a330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Email address:' or . = 'Email address:')]</value>
      <webElementGuid>cf0b779a-9c0c-4dcd-8d55-6e78997d5dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
