<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADMIN</name>
   <tag></tag>
   <elementGuidId>0f6a6d89-075d-41b8-8993-8e4fbcfb5fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.noImage.lastRightNoSpace > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='usernameSection']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18e005ba-e74a-4785-ad82-0b2dd4754ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/admin/manage-contact.ep</value>
      <webElementGuid>06951d5c-bf29-4f02-8429-95829bac9693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADMIN</value>
      <webElementGuid>9f128b13-e018-47cd-86fa-2937a2d6eff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernameSection&quot;)/li[@class=&quot;noImage lastRightNoSpace&quot;]/a[1]</value>
      <webElementGuid>b691a982-d90b-449e-a264-c662417a4111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='usernameSection']/li[4]/a</value>
      <webElementGuid>b067eabd-70bd-44c7-864d-7e34433716fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADMIN')]</value>
      <webElementGuid>ffecc413-7783-422b-884c-a48fa406eba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[1]/following::a[1]</value>
      <webElementGuid>f2eeb29c-6bb3-45f4-ba98-c980b5a8a3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN OUT'])[1]/following::a[2]</value>
      <webElementGuid>4cb1c520-47d5-4712-a0af-4a8ed80f68a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/preceding::a[1]</value>
      <webElementGuid>7a803c33-6b10-4e12-b627-1d1a6f567778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/preceding::a[2]</value>
      <webElementGuid>ce2f3cd1-a5e4-4e4b-b2ce-9270ea0570ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADMIN']/parent::*</value>
      <webElementGuid>8678a08e-5e3d-4e5a-a97d-196a8c5f29c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/admin/manage-contact.ep')]</value>
      <webElementGuid>3dae1905-6c42-4c74-8279-ee409df8e3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>0eb6a23d-a8cb-4375-b31a-8c940f1c9f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/admin/manage-contact.ep' and (text() = 'ADMIN' or . = 'ADMIN')]</value>
      <webElementGuid>0c6e74ba-26fc-4382-8953-279776c41565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
