<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADMIN</name>
   <tag></tag>
   <elementGuidId>87e7691b-c453-4698-bef0-90d6cf1891d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.noImage.lastRightNoSpace > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='usernameSection']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>530e0725-f1a4-4f3d-a71a-19c51b88519b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/admin/manage-contact.ep</value>
      <webElementGuid>88d4ad89-8380-4d53-b35e-c5dffa6730f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADMIN</value>
      <webElementGuid>5901500a-4a75-4919-909d-9d245c2e14de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernameSection&quot;)/li[@class=&quot;noImage lastRightNoSpace&quot;]/a[1]</value>
      <webElementGuid>231d6df9-3521-4472-a5fd-cc60055c0ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='usernameSection']/li[4]/a</value>
      <webElementGuid>ed7d4953-1643-42a5-b274-ceab54283aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADMIN')]</value>
      <webElementGuid>8ce83e71-7ab6-46a1-9b23-091c94b68d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[1]/following::a[1]</value>
      <webElementGuid>a8a8b30c-ae45-4755-ba64-79c69ef1a5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN OUT'])[1]/following::a[2]</value>
      <webElementGuid>648576c4-5750-4cf4-9c10-07c5c71a192c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/preceding::a[1]</value>
      <webElementGuid>ece19aaf-2db4-404b-9b31-a084fcbdfe01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/preceding::a[2]</value>
      <webElementGuid>acf77916-2aaa-4135-85f9-67855c1ef43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADMIN']/parent::*</value>
      <webElementGuid>fcbd0263-8ab9-49f3-bc3c-4845955df29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/admin/manage-contact.ep')]</value>
      <webElementGuid>0fb5c977-0c46-4502-93b2-d1ef5709d668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>2d934429-02e1-43df-bc23-7f02b5791caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/admin/manage-contact.ep' and (text() = 'ADMIN' or . = 'ADMIN')]</value>
      <webElementGuid>ddabdce5-4680-4c49-bd72-2a449cc572dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
