<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SIGN IN</name>
   <tag></tag>
   <elementGuidId>2d696d24-5797-413b-b6cd-2721f4504d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#storefrontSignin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='storefrontSignin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00bac02a-bd34-409a-baac-dac675732f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void();</value>
      <webElementGuid>ec946729-0c9f-4d8c-a0e3-9047862b1ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>storefrontSignin</value>
      <webElementGuid>3be7782b-f94e-4abe-ba44-dd26f2ad977a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:signInMe();</value>
      <webElementGuid>de2e4315-2a78-4608-97c2-4b102ac55e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIGN IN</value>
      <webElementGuid>92ae9a0a-6e3c-4542-9ecc-56760f37385e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storefrontSignin&quot;)</value>
      <webElementGuid>8149ae76-a68d-42a8-8103-5d1a963bac35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='storefrontSignin']</value>
      <webElementGuid>35ed6d63-6105-46f0-b0d1-c79c17af14cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='usernameSection']/li[2]/a</value>
      <webElementGuid>3f38d072-f58a-4443-80ec-9968429d6dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SIGN IN')]</value>
      <webElementGuid>7263b1db-dc2f-450e-a9de-21a3b852c859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance activity is going on, please come after some time.'])[1]/following::a[2]</value>
      <webElementGuid>1e014757-af55-471f-9074-04a322c14d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification:'])[3]/following::a[2]</value>
      <webElementGuid>dd78ecc4-231d-484f-92b6-c9d37dba038e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[1]/preceding::a[1]</value>
      <webElementGuid>5633b6ba-6dda-4b00-99eb-766d77fa9323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/preceding::a[2]</value>
      <webElementGuid>492deebe-3854-418b-9f91-65fe87c9d399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIGN IN']/parent::*</value>
      <webElementGuid>1ee350fb-7145-439e-8628-97536ac0fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void();')]</value>
      <webElementGuid>8d6b6d6b-a0bd-4138-98d3-539055640a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>4e1b7267-d218-470f-aaca-d1bcf1d9418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void();' and @id = 'storefrontSignin' and (text() = 'SIGN IN' or . = 'SIGN IN')]</value>
      <webElementGuid>c1db62e8-9375-4b97-b53e-bfe3857f51ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
