<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TIBCO LOGIN</name>
   <tag></tag>
   <elementGuidId>3e540063-75d7-4910-a69f-e056bd1aa192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#taLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='taLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8d7aeb8-6b2b-46f0-acbe-c5f3a8a67ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ta-button float-right</value>
      <webElementGuid>6ac40770-a5b9-47d1-bf93-e0c9c1837afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taLogin</value>
      <webElementGuid>a5609dd2-dabc-4fa9-9abc-9de858931fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb5b28bf-7595-4051-92bd-5803754da6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIBCO LOGIN</value>
      <webElementGuid>37496c3c-379d-4d56-a41d-bf731e53c4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taLogin&quot;)</value>
      <webElementGuid>012d9f13-db51-4fd9-bec1-8ed11fcc60ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='taLogin']</value>
      <webElementGuid>0d282256-b196-4a8c-b8d5-e3d50ac32393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='login-section']/form/div[2]/app-loginpassword/div/div[2]/button</value>
      <webElementGuid>87ea87cb-cfcc-4356-8a29-a229018a1a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>97b6c2f2-e36a-4649-801a-c14b3d500019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::button[1]</value>
      <webElementGuid>f30e1fcf-479b-4d62-93cd-bb75c8387eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or Sign in with'])[1]/preceding::button[1]</value>
      <webElementGuid>a5816962-21c8-49bd-a37a-cb1b6d93d122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::button[1]</value>
      <webElementGuid>d7f5e95b-dbed-4fdc-9553-75a06c728e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TIBCO LOGIN']/parent::*</value>
      <webElementGuid>878c532e-e775-4e88-9912-c8a08591ef6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>81b75302-c1cd-4da6-a229-99ff294b0a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'taLogin' and @type = 'button' and (text() = 'TIBCO LOGIN' or . = 'TIBCO LOGIN')]</value>
      <webElementGuid>5ad39ddf-02ec-4a4f-9400-164850475b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
