<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_All Products A-Z</name>
   <tag></tag>
   <elementGuidId>cb683449-ad44-4a20-a556-af6cfe6a3b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bodyPDLeftContainer > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyPDLeftContainer']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2d82c24f-a9c3-4c4b-82c7-ed8365ea8971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Products A-Z</value>
      <webElementGuid>24fb184a-2c61-406a-ac25-77401e9b0635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyPDLeftContainer&quot;)/h1[1]</value>
      <webElementGuid>c52b964b-6042-4717-bfaa-1c6ee741bc67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyPDLeftContainer']/h1</value>
      <webElementGuid>2f7c59ab-97d4-4859-be2c-07b6fbb24645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all products A-Z'])[1]/following::h1[1]</value>
      <webElementGuid>084a01a7-524c-4dd3-bb0b-bd7fd73c3686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social'])[1]/following::h1[1]</value>
      <webElementGuid>ca971ac5-624b-4d2f-8b44-abc4ec1ec87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalog'])[1]/preceding::h1[1]</value>
      <webElementGuid>89647cca-5e0a-4355-abc6-420847d16b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Products A-Z']/parent::*</value>
      <webElementGuid>044ccd4c-2c91-425f-b52a-e9cfc5c0fd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h1</value>
      <webElementGuid>362e3f84-47ef-48c1-b45c-9b30bd43eaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'All Products A-Z' or . = 'All Products A-Z')]</value>
      <webElementGuid>e0c3ff16-3953-45fc-bc27-90fba4857406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
