<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Profile</name>
   <tag></tag>
   <elementGuidId>8fa97220-7f1f-4292-906c-8fc12d80a1aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myProfileLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='myProfileLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36f0a299-9544-4d25-867d-779423f3a863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/storefront/customer-profile.ep</value>
      <webElementGuid>d5cc3070-7a35-4a81-aa8e-248aa99e1d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myProfileLink</value>
      <webElementGuid>15009a9a-07e5-4dfd-a792-23a008ad13d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Profile</value>
      <webElementGuid>fdac5aa4-1e76-432b-beb8-4a7a028956dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myProfileLink&quot;)</value>
      <webElementGuid>6ed3ecc8-ecd1-48d6-8eea-2a2d7f7d99f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='myProfileLink']</value>
      <webElementGuid>9197312a-30e6-4536-813e-195fe6e3cdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDwnLeftContainer']/ul/li[2]/a</value>
      <webElementGuid>00b757b1-1965-4846-8ebe-a7d6c0343d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Profile')]</value>
      <webElementGuid>66763f53-b4df-4c56-82bd-012854147dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download History'])[2]/following::a[1]</value>
      <webElementGuid>4c9d5045-00d3-4fd0-98be-67b53fbde68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::a[2]</value>
      <webElementGuid>51c9812e-67cf-4544-b957-1ad0b956f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>d87bc198-8e38-47a1-8997-6643ef1755ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Keys'])[1]/preceding::a[2]</value>
      <webElementGuid>381bbc3f-e428-46ed-8665-36543cbe27d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Profile']/parent::*</value>
      <webElementGuid>85ae2b5e-c68d-4579-80f4-4b5df5893491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/storefront/customer-profile.ep')]</value>
      <webElementGuid>76c22c00-f625-49dc-9681-25be989cd55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]/a</value>
      <webElementGuid>3eaaa64d-2147-4a73-adac-7e44f9da2643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/storefront/customer-profile.ep' and @id = 'myProfileLink' and (text() = 'My Profile' or . = 'My Profile')]</value>
      <webElementGuid>e214096f-309a-4c82-b371-0f9d31382c53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
