<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This site uses cookies. By continuing t_20f0f8</name>
   <tag></tag>
   <elementGuidId>cfd73284-e6ae-4945-bd39-482be666a7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookiesWarningActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cookiesWarningActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2595ef52-298e-4942-947d-c9d6bfb42db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiesWarningActive</value>
      <webElementGuid>91083584-104e-493a-8f34-f27f5523a934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookie-noticebar</value>
      <webElementGuid>6ff04f42-10a7-4676-b72f-c076e3e1d36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This site uses cookies. By continuing to browse the site you are agreeing to our use of cookies.Read our Cookies and Privacy Policy.Notification: Maintenance activity is going on, please come after some time.X</value>
      <webElementGuid>0a8e4109-7b34-49b6-89f6-912f5eac495f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiesWarningActive&quot;)</value>
      <webElementGuid>4c1e5e4b-0d2a-42e4-92d4-e26e38bdc37c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cookiesWarningActive']</value>
      <webElementGuid>6a26438a-5c1e-4e5c-8b10-bcb31e035b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiesWarning']/div</value>
      <webElementGuid>824932f2-eb27-46e2-887e-8a188509e974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='for System Maintenance.'])[1]/following::div[3]</value>
      <webElementGuid>f38f851e-50ba-4375-ab2d-ff2945d5ebbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between'])[1]/following::div[3]</value>
      <webElementGuid>9e089588-2960-4792-be02-13796d4a0bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>a0b3f396-e293-4d1f-bd13-a95b9d85b318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cookiesWarningActive' and (text() = 'This site uses cookies. By continuing to browse the site you are agreeing to our use of cookies.Read our Cookies and Privacy Policy.Notification: Maintenance activity is going on, please come after some time.X' or . = 'This site uses cookies. By continuing to browse the site you are agreeing to our use of cookies.Read our Cookies and Privacy Policy.Notification: Maintenance activity is going on, please come after some time.X')]</value>
      <webElementGuid>c314e238-433c-403e-8b1d-b10d50eb22c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
